import yfinance as yf
import pandas_ta as ta
import pandas as pd
import talib 
import numpy as np
import streamlit as st
import pandas as pd
import numpy as np
my_bar = st.progress(0)
#stocks = ("ALKEM.NS APOLLOHOSP.NS	AARTIIND.NS	ABFRL.NS	ACC.NS	ADANIENT.NS	ADANIPORTS.NS	ALKEM.NS	AMARAJABAT.NS	APLLTD.NS	APOLLOHOSP.NS	APOLLOTYRE.NS	ASHOKLEY.NS	ASIANPAINT.NS	AUBANK.NS	AUROPHARMA.NS	AXISBANK.NS	BAJAJ-AUTO.NS	BAJAJFINSV.NS	BAJFINANCE.NS	BALKRISIND.NS	BANDHANBNK.NS	BANKBARODA.NS	BATAINDIA.NS	BEL.NS	BERGEPAINT.NS	BHARATFORG.NS	BHARTIARTL.NS	BHEL.NS	BIOCON.NS	BOSCHLTD.NS	BPCL.NS	BRITANNIA.NS	CANBK.NS	CHOLAFIN.NS	CIPLA.NS	COALINDIA.NS	COFORGE.NS	COLPAL.NS	CONCOR.NS	COROMANDEL.NS	CUB.NS	CUMMINSIND.NS	DABUR.NS	DEEPAKNTR.NS	DIVISLAB.NS	DLF.NS	DRREDDY.NS	EICHERMOT.NS	ESCORTS.NS	EXIDEIND.NS	FEDERALBNK.NS	GAIL.NS	GLENMARK.NS	GMRINFRA.NS	GODREJCP.NS	GODREJPROP.NS	GRANULES.NS	GRASIM.NS	GUJGASLTD.NS	HAVELLS.NS	HCLTECH.NS	HdfC.NS	HdfCAMC.NS	HdfCBANK.NS	HdfCLIFE.NS	HEROMOTOCO.NS	HINDALCO.NS	HINDPETRO.NS	HINDUNILVR.NS	IBULHSGFIN.NS	ICICIBANK.NS	ICICIGI.NS	ICICIPRULI.NS	IDEA.NS	IdfCFIRSTB.NS	IGL.NS	INDHOTEL.NS	INDIGO.NS	INDUSINDBK.NS	INDUSTOWER.NS	INFY.NS	IOC.NS	IRCTC.NS	ITC.NS	JINDALSTEL.NS	JSWSTEEL.NS	JUBLFOOD.NS	KOTAKBANK.NS	L&TFH.NS	LALPATHLAB.NS	LICHSGFIN.NS	LT.NS	LTI.NS	LTTS.NS	LUPIN.NS	M&M.NS	M&MFIN.NS	MANAPPURAM.NS	MARICO.NS	MARUTI.NS	MCDOWELL-N.NS	METROPOLIS.NS	MFSL.NS	MGL.NS	MINDTREE.NS	MPHASIS.NS	MRF.NS	MUTHOOTFIN.NS	NAM-INDIA.NS	NATIONALUM.NS	NAUKRI.NS	NAVINFLUOR.NS	NESTLEIND.NS	NMDC.NS	NTPC.NS	ONGC.NS	PAGEIND.NS	PEL.NS	PETRONET.NS	PFC.NS	PFIZER.NS	PIDILITIND.NS	PIIND.NS	PNB.NS	POWERGRID.NS	PVR.NS	RAMCOCEM.NS	RBLBANK.NS	RECLTD.NS	RELIANCE.NS	SAIL.NS	SBILIFE.NS	SBIN.NS	SHREECEM.NS	SIEMENS.NS	SRF.NS	SRTRANSFIN.NS	SUNPHARMA.NS	SUNTV.NS	TATACHEM.NS	TATACONSUM.NS	TATAMOTORS.NS	TATAPOWER.NS	TATASTEEL.NS	TCS.NS	TECHM.NS	TITAN.NS	TORNTPHARM.NS	TORNTPOWER.NS	TRENT.NS	TVSMOTOR.NS	UBL.NS	ULTRACEMCO.NS	UPL.NS	VEDL.NS	VOLTAS.NS	WIPRO.NS	ZEEL.NS	ASTRAL.NS	STAR.NS	CANFINHOME.NS	DIXON.NS	HAL.NS	IEX.NS	INDIAMART.NS	IPCALAB.NS	MCX.NS	OFSS.NS	POLYCAB.NS	SYNGENE.NS")
def stock():
        
    stocks = ("ALKEM.NS APOLLOHOSP.NS		ABFRL.NS	ACC.NS	ADANIENT.NS	ADANIPORTS.NS	ALKEM.NS	AMARAJABAT.NS	APLLTD.NS	APOLLOHOSP.NS	APOLLOTYRE.NS	ASHOKLEY.NS	ASIANPAINT.NS	AUBANK.NS	AUROPHARMA.NS	AXISBANK.NS	BAJAJ-AUTO.NS	BAJAJFINSV.NS	BAJFINANCE.NS	BALKRISIND.NS	BANDHANBNK.NS	BANKBARODA.NS	BATAINDIA.NS	BEL.NS	BERGEPAINT.NS	BHARATFORG.NS	BHARTIARTL.NS	BHEL.NS	BIOCON.NS	BOSCHLTD.NS	BPCL.NS	BRITANNIA.NS	CANBK.NS	CHOLAFIN.NS	CIPLA.NS	COALINDIA.NS	COFORGE.NS	COLPAL.NS 	CONCOR.NS	COROMANDEL.NS	CUB.NS	CUMMINSIND.NS	DABUR.NS	DEEPAKNTR.NS	DIVISLAB.NS	DLF.NS	DRREDDY.NS	EICHERMOT.NS	ESCORTS.NS	EXIDEIND.NS	FEDERALBNK.NS	GAIL.NS	GLENMARK.NS	GMRINFRA.NS	GODREJCP.NS	GODREJPROP.NS	GRANULES.NS	GRASIM.NS	GUJGASLTD.NS	HAVELLS.NS	HCLTECH.NS	HdfC.NS	HdfCAMC.NS	HdfCBANK.NS	HdfCLIFE.NS	HEROMOTOCO.NS	HINDALCO.NS	HINDPETRO.NS	HINDUNILVR.NS	IBULHSGFIN.NS	ICICIBANK.NS	ICICIGI.NS	ICICIPRULI.NS	IDEA.NS	IdfCFIRSTB.NS	IGL.NS	INDHOTEL.NS	INDIGO.NS	INDUSINDBK.NS	INDUSTOWER.NS	INFY.NS	IOC.NS	IRCTC.NS	ITC.NS	JINDALSTEL.NS	JSWSTEEL.NS	JUBLFOOD.NS	KOTAKBANK.NS	L&TFH.NS 	LALPATHLAB.NS	LICHSGFIN.NS	LT.NS	LTI.NS	LTTS.NS	LUPIN.NS	M&M.NS	M&MFIN.NS	MANAPPURAM.NS	MARICO.NS	MARUTI.NS	MCDOWELL-N.NS	METROPOLIS.NS	MFSL.NS	MGL.NS	MINDTREE.NS	MPHASIS.NS	MRF.NS	MUTHOOTFIN.NS	NAM-INDIA.NS	NATIONALUM.NS	NAUKRI.NS	NAVINFLUOR.NS	NESTLEIND.NS	NMDC.NS	NTPC.NS	ONGC.NS	PAGEIND.NS	PEL.NS	PETRONET.NS	PFC.NS	PFIZER.NS	PIDILITIND.NS	PIIND.NS	PNB.NS	POWERGRID.NS	PVR.NS	RAMCOCEM.NS	RBLBANK.NS	RECLTD.NS	RELIANCE.NS	SAIL.NS	SBILIFE.NS	SBIN.NS	SHREECEM.NS	SIEMENS.NS	SRF.NS	SRTRANSFIN.NS	SUNPHARMA.NS	SUNTV.NS	TATACHEM.NS	TATACONSUM.NS	TATAMOTORS.NS	TATAPOWER.NS	TATASTEEL.NS	TCS.NS	TECHM.NS	TITAN.NS	TORNTPHARM.NS")
    #stocks = ("ALKEM.NS APOLLOHOSP.NS		ABFRL.NS")
    data = yf.download(stocks,period="5d",interval="5m").dropna()
    df = pd.DataFrame()
    numa = 1
    for b in list(data.columns.levels[1]):
        a = pd.DataFrame()
        a["Stockname"] = b
        a["Close"] =  data['Close'][b]
        a["High"] = data["High"][b]
        a["Low"] = data["Low"][b]
        a["Volume"] = data["Volume"][b]
        a["Open"] = data["Open"][b]
        a["Close"] = data["Close"][b]
        hh = a["High"]
        ll = a["Low"]
        vv = a["Volume"]
        oo = a["Open"]
        cc = a["Close"]
        a["Stockname"] = b
        adx = ta.adx(high=a["High"],low=a["Low"],close=a["Close"],length=14)
        a["rsi"] = ta.rsi(high=a["High"],low=a["Low"],close=a["Close"],length=14)
        bb = ta.bbands(cc,length=20,std=1)
        a["vwap"] = ta.vwap(high=hh,low=ll,close=cc,volume=vv)

        a["adx"] = 0
        a["adx"] = adx["ADX_14"]
        a["+di"] = adx["DMP_14"]
        a["-di"] = adx["DMN_14"]
        a["bb-u"] = bb["BBU_20_1.0"]
        a["bb-m"] = bb["BBM_20_1.0"]
        a["bb-l"] = bb["BBL_20_1.0"]
        a = a[-2:-1]

        a["bbsignal"] = np.where(((a["Open"] < a["bb-u"]) & (a["Close"] > a["bb-u"]) & (a["Close"] > a["vwap"]) & (a["+di"] > 25) & (a["rsi"] > 55)) ,"Buy","")
        sig = a[a["bbsignal"]=="Buy"]
        append = pd.DataFrame(sig)
        df = df.append(append)
        numa = numa + (100/len(data.columns.levels[1]))
        my_bar.progress(int(numa))

    st.dataframe(df)
if st.button('Run FIle'):
    stock()
    

#st.table(data)


